language: python
python:
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
os:
  - linux
sudo: required
dist: xenial
matrix:
  allow_failures:
    - os: linux
      python: "3.8-dev"
    - os: linux
      python: "nightly"

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - python -V
  - travis_retry pip install --upgrade pip wheel   # get pip >= 7, which caches built packages
  - travis_wait 20 pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - pip install pylint
  - pip install mypy
install:
  - ./setup.py install
script:
  - python -m unittest -v
  - mypy autovar --ignore-missing-import
  - coverage run --source autovar setup.py test
  - coverage report
after_success:
  - pylint libact
  - codecov
